### PR TITLE
Fix typo in readme

### PR DESCRIPTION
**Pull request by jyn514**

### CODE REVIEW

**Comment by danielhenrymantilla** [comment]
Thanks! Now that we are at it, can you fix the line 67 with the missing `does`? I'm ~~too lazy for that~~ looking to minimize the number of typo-related commits 😁

**Comment by jyn514** [comment]
Sure, done :laughing:

**Review by danielhenrymantilla — APPROVED** [review]
Tahnks!

**Comment by jyn514** [comment]
> Tahnks!

Even your typos have typos! 😂 

You're very welcome :)

**Pull request merged**
